import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="  object-cover w-full bg-cover h-screen grid justify-center content-center bg-gradient-to-tl from-blue-700 to-black">
      <img
        src="img/bg-4.jpg"
        className=" absolute h-full w-full object-cover mix-blend-overlay"
      />

      <div className={styles.container}>
        <Head>
          <title className="bg-slate-100">Kaph Global - Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to{" "}
            <a href="https://kaphglobal.com" className="text-white">
              Kaph Global Solutions
            </a>
          </h1>

          <p className={styles.description}>Page is Under Construction </p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <p>
              Powered by{" "}
              <span className=" text-blue-300"> PointX and Zest</span>
            </p>
          </a>
        </footer>
      </div>
    </div>
  );
}
