import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="  object-cover w-full bg-cover h-screen grid justify-center content-center bg-gradient-to-t from-gray-700 to-gray-700">
      <img
        src="img/bg-4.jpg"
        className=" absolute h-full w-full object-cover mix-blend-overlay"
      />

      <div className={styles.container}>
        <Head>
          <title className="bg-slate-100">Kaph Global - Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to{" "}
            <a href="https://kaphglobal.com" className="text-white">
              Kaph Global Solutions
            </a>
          </h1>

          <p className={styles.description}>Page is Under Construction </p>

          <button className="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center">
            <svg
              className="fill-current w-4 h-4 mr-2"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" />
            </svg>
            <span>Contact us </span>
          </button>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <p>
              Powered by{" "}
              <span className=" text-blue-200"> PointX and Zest</span>
            </p>
          </a>
        </footer>
      </div>
    </div>
  );
}
